Vagrant.configure("2") do |config|
 # config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "centos" do |centos|
    centos.vm.box = "generic/centos9s"
    centos.vm.network "private_network", ip: "192.168.56.26"

  # vm ram settings
  #  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end

  # Provisioning this centos system with readymade static website ready to run on the given private ip.
 centos.vm.provision "shell", inline: <<-SHELL
  #apt update
   yum install httpd wget unzip -y
   systemctl start httpd
   systemctl enable httpd
   firewall-cmd --permanent --add-service=http
   firewall-cmd --reload
   cd /tmp/
   wget https://www.tooplate.com/zip-templates/2119_gymso_fitness.zip
   unzip -o 2119_gymso_fitness.zip
   cp -r 2119_gymso_fitness/* /var/www/html/

   systemctl restart httpd
   SHELL
  end

 config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
    ubuntu.vm.network "private_network", ip: "192.168.56.27"

  # vm ram settings
  #  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end

  # Provisioning the ubuntu system with readymade setup format for the wordpress on the given ip address.
  ubuntu.vm.provision "shell", inline: <<-SHELL
  apt update -y

  apt install -y apache2 \
    ghostscript \
    libapache2-mod-php \
    mysql-server \
    php \
    php-bcmath \
    php-curl \
    php-imagick \
    php-intl \
    php-json \
    php-mbstring \
    php-mysql \
    php-xml \
    php-zip \
    ufw

  systemctl enable --now apache2
  systemctl enable --now mysql

  mkdir -p /srv/www
  chown www-data:www-data /srv/www

  curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www

  cp /vagrant/wordpress.conf /etc/apache2/sites-available/wordpress.conf

  a2ensite wordpress
  a2enmod rewrite
  a2dissite 000-default
  systemctl reload apache2

  mysql -u root -e "CREATE DATABASE wordpress;"
  mysql -u root -e "CREATE USER 'wordpress'@'localhost' IDENTIFIED BY 'nix123';"
  mysql -u root -e "GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO 'wordpress'@'localhost';"
  mysql -u root -e "FLUSH PRIVILEGES;"

  ufw allow http
  ufw allow https
  ufw --force enable

  sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php
  sudo -u www-data sed -i 's/database_name_here/wordpress/' /srv/www/wordpress/wp-config.php
  sudo -u www-data sed -i 's/username_here/wordpress/' /srv/www/wordpress/wp-config.php
  sudo -u www-data sed -i 's/password_here/nix123/' /srv/www/wordpress/wp-config.php
 SHELL
 end

end
